//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace DWMS_OCR.AcceptDocWebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'UsingAddressing' from namespace 'http://www.w3.org/2006/05/addressing/wsdl' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BE01JAcceptDocSoapBinding", Namespace="http://ejb.be01.hdb.gov.sg")]
    public partial class BE01JAcceptDocService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback acceptDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback lockDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback enquireAcceptDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BE01JAcceptDocService() {
            this.Url = global::DWMS_OCR.Properties.Settings.Default.DWMS_OCR_Service_AcceptDocWebRef_BE01JAcceptDocService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event acceptDocumentCompletedEventHandler acceptDocumentCompleted;
        
        /// <remarks/>
        public event lockDocumentCompletedEventHandler lockDocumentCompleted;
        
        /// <remarks/>
        public event enquireAcceptDocumentCompletedEventHandler enquireAcceptDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("acceptDocument", RequestNamespace="http://ejb.be01.hdb.gov.sg", ResponseNamespace="http://ejb.be01.hdb.gov.sg", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("acceptDocumentReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BE01JOutputDTO acceptDocument([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JAuthenticationDTO authentication, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JSystemInfoDTO systemDTO, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JBusinessInfoDTO businessDTO) {
            object[] results = this.Invoke("acceptDocument", new object[] {
                        authentication,
                        systemDTO,
                        businessDTO});
            return ((BE01JOutputDTO)(results[0]));
        }
        
        /// <remarks/>
        public void acceptDocumentAsync(BE01JAuthenticationDTO authentication, BE01JSystemInfoDTO systemDTO, BE01JBusinessInfoDTO businessDTO) {
            this.acceptDocumentAsync(authentication, systemDTO, businessDTO, null);
        }
        
        /// <remarks/>
        public void acceptDocumentAsync(BE01JAuthenticationDTO authentication, BE01JSystemInfoDTO systemDTO, BE01JBusinessInfoDTO businessDTO, object userState) {
            if ((this.acceptDocumentOperationCompleted == null)) {
                this.acceptDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacceptDocumentOperationCompleted);
            }
            this.InvokeAsync("acceptDocument", new object[] {
                        authentication,
                        systemDTO,
                        businessDTO}, this.acceptDocumentOperationCompleted, userState);
        }
        
        private void OnacceptDocumentOperationCompleted(object arg) {
            if ((this.acceptDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acceptDocumentCompleted(this, new acceptDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("lockDocument", RequestNamespace="http://ejb.be01.hdb.gov.sg", ResponseNamespace="http://ejb.be01.hdb.gov.sg", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("lockDocumentReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BE01JOutputDTO lockDocument([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JAuthenticationDTO authentication, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JSystemInfoDTO systemDTO, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JBusinessInfoDTO businessDTO) {
            object[] results = this.Invoke("lockDocument", new object[] {
                        authentication,
                        systemDTO,
                        businessDTO});
            return ((BE01JOutputDTO)(results[0]));
        }
        
        /// <remarks/>
        public void lockDocumentAsync(BE01JAuthenticationDTO authentication, BE01JSystemInfoDTO systemDTO, BE01JBusinessInfoDTO businessDTO) {
            this.lockDocumentAsync(authentication, systemDTO, businessDTO, null);
        }
        
        /// <remarks/>
        public void lockDocumentAsync(BE01JAuthenticationDTO authentication, BE01JSystemInfoDTO systemDTO, BE01JBusinessInfoDTO businessDTO, object userState) {
            if ((this.lockDocumentOperationCompleted == null)) {
                this.lockDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlockDocumentOperationCompleted);
            }
            this.InvokeAsync("lockDocument", new object[] {
                        authentication,
                        systemDTO,
                        businessDTO}, this.lockDocumentOperationCompleted, userState);
        }
        
        private void OnlockDocumentOperationCompleted(object arg) {
            if ((this.lockDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lockDocumentCompleted(this, new lockDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("enquireAcceptDocument", RequestNamespace="http://ejb.be01.hdb.gov.sg", ResponseNamespace="http://ejb.be01.hdb.gov.sg", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("enquireAcceptDocumentReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BE01JOutputDTO enquireAcceptDocument([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JAuthenticationDTO authentication, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] BE01JAcceptEnquiryInputDTO acceptEnqInput) {
            object[] results = this.Invoke("enquireAcceptDocument", new object[] {
                        authentication,
                        acceptEnqInput});
            return ((BE01JOutputDTO)(results[0]));
        }
        
        /// <remarks/>
        public void enquireAcceptDocumentAsync(BE01JAuthenticationDTO authentication, BE01JAcceptEnquiryInputDTO acceptEnqInput) {
            this.enquireAcceptDocumentAsync(authentication, acceptEnqInput, null);
        }
        
        /// <remarks/>
        public void enquireAcceptDocumentAsync(BE01JAuthenticationDTO authentication, BE01JAcceptEnquiryInputDTO acceptEnqInput, object userState) {
            if ((this.enquireAcceptDocumentOperationCompleted == null)) {
                this.enquireAcceptDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenquireAcceptDocumentOperationCompleted);
            }
            this.InvokeAsync("enquireAcceptDocument", new object[] {
                        authentication,
                        acceptEnqInput}, this.enquireAcceptDocumentOperationCompleted, userState);
        }
        
        private void OnenquireAcceptDocumentOperationCompleted(object arg) {
            if ((this.enquireAcceptDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enquireAcceptDocumentCompleted(this, new enquireAcceptDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JAuthenticationDTO {
        
        private string userNameField;
        
        private string passWordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string passWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.enq.be01.hdb.gov.sg")]
    public partial class BE01JAcceptEnquiryInputDTO {
        
        private string cmDocumentIdField;
        
        private string businessTransactionNumberField;
        
        private string businessRefNumberField;
        
        private string customerIdFromSourceField;
        
        private string docIdField;
        
        private string docIdSubField;
        
        private System.Nullable<System.DateTime> docStartDateField;
        
        private System.Nullable<System.DateTime> docEndDateField;
        
        private string identityNoSubField;
        
        private string customerIdSubFromSourceField;
        
        private System.Nullable<System.DateTime> docAcceptTimeField;
        
        private string acceptUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cmDocumentId {
            get {
                return this.cmDocumentIdField;
            }
            set {
                this.cmDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string businessTransactionNumber {
            get {
                return this.businessTransactionNumberField;
            }
            set {
                this.businessTransactionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string businessRefNumber {
            get {
                return this.businessRefNumberField;
            }
            set {
                this.businessRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdFromSource {
            get {
                return this.customerIdFromSourceField;
            }
            set {
                this.customerIdFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docIdSub {
            get {
                return this.docIdSubField;
            }
            set {
                this.docIdSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docStartDate {
            get {
                return this.docStartDateField;
            }
            set {
                this.docStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docEndDate {
            get {
                return this.docEndDateField;
            }
            set {
                this.docEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNoSub {
            get {
                return this.identityNoSubField;
            }
            set {
                this.identityNoSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdSubFromSource {
            get {
                return this.customerIdSubFromSourceField;
            }
            set {
                this.customerIdSubFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docAcceptTime {
            get {
                return this.docAcceptTimeField;
            }
            set {
                this.docAcceptTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string acceptUserId {
            get {
                return this.acceptUserIdField;
            }
            set {
                this.acceptUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01JSystemOutput {
        
        private string updateSystemIdField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        private System.Nullable<System.DateTime> updateTimeField;
        
        private string fileSystemIdField;
        
        private System.Nullable<System.DateTime> fileDateField;
        
        private string verificationUserIdField;
        
        private string completenessUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string updateSystemId {
            get {
                return this.updateSystemIdField;
            }
            set {
                this.updateSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fileSystemId {
            get {
                return this.fileSystemIdField;
            }
            set {
                this.fileSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> fileDate {
            get {
                return this.fileDateField;
            }
            set {
                this.fileDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string verificationUserId {
            get {
                return this.verificationUserIdField;
            }
            set {
                this.verificationUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string completenessUserId {
            get {
                return this.completenessUserIdField;
            }
            set {
                this.completenessUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01PersonOutput {
        
        private bool resultFlgField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string customerIdFromSourceField;
        
        private string identityNoField;
        
        private string identityTypeField;
        
        private string customerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultFlg {
            get {
                return this.resultFlgField;
            }
            set {
                this.resultFlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdFromSource {
            get {
                return this.customerIdFromSourceField;
            }
            set {
                this.customerIdFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNo {
            get {
                return this.identityNoField;
            }
            set {
                this.identityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01ImageOutput {
        
        private bool resultFlgField;
        
        private string cmDocumentIdField;
        
        private string dwmsDocumentIdField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private BE01PersonOutput[] personOutputListField;
        
        private string numDocGroupField;
        
        private string numDocAcceptField;
        
        private string numDocStatusField;
        
        private string acceptUserIdField;
        
        private System.Nullable<System.DateTime> tmeDocAcceptField;
        
        private BE01JSystemOutput systemInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultFlg {
            get {
                return this.resultFlgField;
            }
            set {
                this.resultFlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cmDocumentId {
            get {
                return this.cmDocumentIdField;
            }
            set {
                this.cmDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dwmsDocumentId {
            get {
                return this.dwmsDocumentIdField;
            }
            set {
                this.dwmsDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01PersonOutput[] personOutputList {
            get {
                return this.personOutputListField;
            }
            set {
                this.personOutputListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string numDocGroup {
            get {
                return this.numDocGroupField;
            }
            set {
                this.numDocGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string numDocAccept {
            get {
                return this.numDocAcceptField;
            }
            set {
                this.numDocAcceptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string numDocStatus {
            get {
                return this.numDocStatusField;
            }
            set {
                this.numDocStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string acceptUserId {
            get {
                return this.acceptUserIdField;
            }
            set {
                this.acceptUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> tmeDocAccept {
            get {
                return this.tmeDocAcceptField;
            }
            set {
                this.tmeDocAcceptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BE01JSystemOutput systemInfo {
            get {
                return this.systemInfoField;
            }
            set {
                this.systemInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01DocumentOutput {
        
        private bool resultFlgField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private BE01ImageOutput[] imageOutputListField;
        
        private string docIdField;
        
        private string docIdSubField;
        
        private System.Nullable<System.DateTime> docStartDateField;
        
        private System.Nullable<System.DateTime> docEndDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultFlg {
            get {
                return this.resultFlgField;
            }
            set {
                this.resultFlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01ImageOutput[] imageOutputList {
            get {
                return this.imageOutputListField;
            }
            set {
                this.imageOutputListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docIdSub {
            get {
                return this.docIdSubField;
            }
            set {
                this.docIdSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docStartDate {
            get {
                return this.docStartDateField;
            }
            set {
                this.docStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docEndDate {
            get {
                return this.docEndDateField;
            }
            set {
                this.docEndDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01CustomerOutput {
        
        private bool resultFlgField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private BE01DocumentOutput[] documentOutputListField;
        
        private string customerIdFromSourceField;
        
        private string identityNoField;
        
        private string identityTypeField;
        
        private string customerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultFlg {
            get {
                return this.resultFlgField;
            }
            set {
                this.resultFlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01DocumentOutput[] documentOutputList {
            get {
                return this.documentOutputListField;
            }
            set {
                this.documentOutputListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdFromSource {
            get {
                return this.customerIdFromSourceField;
            }
            set {
                this.customerIdFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNo {
            get {
                return this.identityNoField;
            }
            set {
                this.identityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01BusinessOutput {
        
        private bool resultFlgField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private BE01CustomerOutput[] customerOutputListField;
        
        private string businessTransactionNumberField;
        
        private string businessRefNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultFlg {
            get {
                return this.resultFlgField;
            }
            set {
                this.resultFlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01CustomerOutput[] customerOutputList {
            get {
                return this.customerOutputListField;
            }
            set {
                this.customerOutputListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string businessTransactionNumber {
            get {
                return this.businessTransactionNumberField;
            }
            set {
                this.businessTransactionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string businessRefNumber {
            get {
                return this.businessRefNumberField;
            }
            set {
                this.businessRefNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.filing.be01.hdb.gov.sg")]
    public partial class BE01JOutputDTO {
        
        private string obsResultFlagField;
        
        private string obsErrorCodeField;
        
        private string obsServerErrorMessageField;
        
        private BE01BusinessOutput businessOutputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string obsResultFlag {
            get {
                return this.obsResultFlagField;
            }
            set {
                this.obsResultFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string obsErrorCode {
            get {
                return this.obsErrorCodeField;
            }
            set {
                this.obsErrorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string obsServerErrorMessage {
            get {
                return this.obsServerErrorMessageField;
            }
            set {
                this.obsServerErrorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BE01BusinessOutput businessOutput {
            get {
                return this.businessOutputField;
            }
            set {
                this.businessOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JPersonInfoDTO {
        
        private string identityNoField;
        
        private string identityTypeField;
        
        private string customerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNo {
            get {
                return this.identityNoField;
            }
            set {
                this.identityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JPersonIdentityInfoDTO {
        
        private string customerIdFromSourceField;
        
        private string identityNoField;
        
        private string identityTypeField;
        
        private string customerNameField;
        
        private BE01JPersonInfoDTO personInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdFromSource {
            get {
                return this.customerIdFromSourceField;
            }
            set {
                this.customerIdFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNo {
            get {
                return this.identityNoField;
            }
            set {
                this.identityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BE01JPersonInfoDTO personInfo {
            get {
                return this.personInfoField;
            }
            set {
                this.personInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JImageInfoDTO {
        
        private string imageUrlField;
        
        private string imageNameField;
        
        private string imageSizeField;
        
        private System.Nullable<System.DateTime> docRecievedSourceDateField;
        
        private string cmDocumentIdField;
        
        private string certificateNumberField;
        
        private System.Nullable<System.DateTime> certificateDateField;
        
        private BE01JPersonIdentityInfoDTO[] personInfoListField;
        
        private bool vrfdWithOriginalField;
        
        private string imageConditionField;
        
        private string dwmsDocumentIdField;
        
        private string localForeignField;
        
        private string marriageTypeField;
        
        private string imageAcceptedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string imageName {
            get {
                return this.imageNameField;
            }
            set {
                this.imageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string imageSize {
            get {
                return this.imageSizeField;
            }
            set {
                this.imageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docRecievedSourceDate {
            get {
                return this.docRecievedSourceDateField;
            }
            set {
                this.docRecievedSourceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cmDocumentId {
            get {
                return this.cmDocumentIdField;
            }
            set {
                this.cmDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string certificateNumber {
            get {
                return this.certificateNumberField;
            }
            set {
                this.certificateNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> certificateDate {
            get {
                return this.certificateDateField;
            }
            set {
                this.certificateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01JPersonIdentityInfoDTO[] personInfoList {
            get {
                return this.personInfoListField;
            }
            set {
                this.personInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool vrfdWithOriginal {
            get {
                return this.vrfdWithOriginalField;
            }
            set {
                this.vrfdWithOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string imageCondition {
            get {
                return this.imageConditionField;
            }
            set {
                this.imageConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dwmsDocumentId {
            get {
                return this.dwmsDocumentIdField;
            }
            set {
                this.dwmsDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string localForeign {
            get {
                return this.localForeignField;
            }
            set {
                this.localForeignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string marriageType {
            get {
                return this.marriageTypeField;
            }
            set {
                this.marriageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string imageAccepted {
            get {
                return this.imageAcceptedField;
            }
            set {
                this.imageAcceptedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JDocumentInfoDTO {
        
        private string docIdField;
        
        private string docIdSubField;
        
        private string docDescriptionField;
        
        private System.Nullable<System.DateTime> docStartDateField;
        
        private System.Nullable<System.DateTime> docEndDateField;
        
        private string identityNoSubField;
        
        private string customerIdSubFromSourceField;
        
        private BE01JImageInfoDTO[] imageInfoListField;
        
        private string docChannelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docIdSub {
            get {
                return this.docIdSubField;
            }
            set {
                this.docIdSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docDescription {
            get {
                return this.docDescriptionField;
            }
            set {
                this.docDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docStartDate {
            get {
                return this.docStartDateField;
            }
            set {
                this.docStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> docEndDate {
            get {
                return this.docEndDateField;
            }
            set {
                this.docEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNoSub {
            get {
                return this.identityNoSubField;
            }
            set {
                this.identityNoSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdSubFromSource {
            get {
                return this.customerIdSubFromSourceField;
            }
            set {
                this.customerIdSubFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01JImageInfoDTO[] imageInfoList {
            get {
                return this.imageInfoListField;
            }
            set {
                this.imageInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docChannel {
            get {
                return this.docChannelField;
            }
            set {
                this.docChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JCustomerInfoDTO {
        
        private string customerIdFromSourceField;
        
        private string identityNoField;
        
        private string identityTypeField;
        
        private string customerNameField;
        
        private int docCounterField;
        
        private BE01JDocumentInfoDTO[] documentInfoListField;
        
        private string customerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerIdFromSource {
            get {
                return this.customerIdFromSourceField;
            }
            set {
                this.customerIdFromSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityNo {
            get {
                return this.identityNoField;
            }
            set {
                this.identityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int docCounter {
            get {
                return this.docCounterField;
            }
            set {
                this.docCounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01JDocumentInfoDTO[] documentInfoList {
            get {
                return this.documentInfoListField;
            }
            set {
                this.documentInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string customerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JBusinessInfoDTO {
        
        private string businessTransactionNumberField;
        
        private string businessRefNumberField;
        
        private BE01JCustomerInfoDTO[] customerInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string businessTransactionNumber {
            get {
                return this.businessTransactionNumberField;
            }
            set {
                this.businessTransactionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string businessRefNumber {
            get {
                return this.businessRefNumberField;
            }
            set {
                this.businessRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BE01JCustomerInfoDTO[] customerInfoList {
            get {
                return this.customerInfoListField;
            }
            set {
                this.customerInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.service.web.be01.hdb.gov.sg")]
    public partial class BE01JSystemInfoDTO {
        
        private string updateSystemIdField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        private System.Nullable<System.DateTime> updateTimeField;
        
        private string fileSystemIdField;
        
        private System.Nullable<System.DateTime> fileDateField;
        
        private string verificationUserIdField;
        
        private string completenessUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string updateSystemId {
            get {
                return this.updateSystemIdField;
            }
            set {
                this.updateSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fileSystemId {
            get {
                return this.fileSystemIdField;
            }
            set {
                this.fileSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> fileDate {
            get {
                return this.fileDateField;
            }
            set {
                this.fileDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string verificationUserId {
            get {
                return this.verificationUserIdField;
            }
            set {
                this.verificationUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string completenessUserId {
            get {
                return this.completenessUserIdField;
            }
            set {
                this.completenessUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void acceptDocumentCompletedEventHandler(object sender, acceptDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class acceptDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal acceptDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BE01JOutputDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BE01JOutputDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void lockDocumentCompletedEventHandler(object sender, lockDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lockDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lockDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BE01JOutputDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BE01JOutputDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void enquireAcceptDocumentCompletedEventHandler(object sender, enquireAcceptDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enquireAcceptDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enquireAcceptDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BE01JOutputDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BE01JOutputDTO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591