//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWMS_OCR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://intranet-appu.hdb.gov.sg:80/webapp/BE01EBCstmrDocService/services/BE01JAcc" +
            "eptDoc")]
        public string DWMS_OCR_Service_AcceptDocWebRef_BE01JAcceptDocService {
            get {
                return ((string)(this["DWMS_OCR_Service_AcceptDocWebRef_BE01JAcceptDocService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://intranet-appu.hdb.gov.sg:80/webapp/BE01EBCstmrDocService/services/BE01JVer" +
            "ifyDoc")]
        public string DWMS_OCR_Service_VerifyDocWebRef_BE01JVerifyDocService {
            get {
                return ((string)(this["DWMS_OCR_Service_VerifyDocWebRef_BE01JVerifyDocService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/BP27WSDwmsWeb/services/BP27JDwmsPersonInfoUpdate")]
        public string DWMS_OCR_Service_PersonInfoUpdateWebRef_BP27JDwmsPersonInfoUpdateService {
            get {
                return ((string)(this["DWMS_OCR_Service_PersonInfoUpdateWebRef_BP27JDwmsPersonInfoUpdateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HIEND-PC009\\FONTZ;Initial Catalog=DWMSDB;Persist Security Info=True;U" +
            "ser ID=sa;Password=abc123;Connection Timeout=120")]
        public string ASPNETDBConnectionString {
            get {
                return ((string)(this["ASPNETDBConnectionString"]));
            }
        }
    }
}
